/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f6bea6ca-ec3a-4438-9571-5a1eaba4d080",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_T8qTCLaCS",
    "aws_user_pools_web_client_id": "7r2435gt29c7do2fgnq7bbblec",
    "oauth": {}
};


export default awsmobile;
